{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "nk-backend.fullname" . }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.store }}
    kind: ClusterSecretStore
  target:
    name: {{ include "nk-backend.fullname" . }}
  data:
{{- if .Values.runtime.databaseEnabled }}
    - secretKey: __APP_ENV_PREFIX___DB_HOST
      remoteRef:
        key: {{ .Values.externalSecrets.key }}
        property: __APP_ENV_PREFIX___DB_HOST
    - secretKey: __APP_ENV_PREFIX___DB_USER
      remoteRef:
        key: {{ .Values.externalSecrets.key }}
        property: __APP_ENV_PREFIX___DB_USER
    - secretKey: __APP_ENV_PREFIX___DB_PASS
      remoteRef:
        key: {{ .Values.externalSecrets.key }}
        property: __APP_ENV_PREFIX___DB_PASS
    - secretKey: __APP_ENV_PREFIX___DB_BASE
      remoteRef:
        key: {{ .Values.externalSecrets.key }}
        property: __APP_ENV_PREFIX___DB_BASE
{{- end }}
{{- if .Values.runtime.identityEnabled }}
    - secretKey: __APP_ENV_PREFIX___USERS_SECRET
      remoteRef:
        key: {{ .Values.externalSecrets.key }}
        property: __APP_ENV_PREFIX___USERS_SECRET
    - secretKey: __APP_ENV_PREFIX___AUTH_STORE_BACKEND
      remoteRef:
        key: {{ .Values.externalSecrets.key }}
        property: __APP_ENV_PREFIX___AUTH_STORE_BACKEND
    - secretKey: __APP_ENV_PREFIX___METRICS_AUTH_TOKEN
      remoteRef:
        key: {{ .Values.externalSecrets.key }}
        property: __APP_ENV_PREFIX___METRICS_AUTH_TOKEN
{{- if or (eq .Values.runtime.authStoreBackend "redis") (eq .Values.runtime.authStoreBackend "redis-or-sql") }}
    - secretKey: __APP_ENV_PREFIX___REDIS_HOST
      remoteRef:
        key: {{ .Values.externalSecrets.key }}
        property: __APP_ENV_PREFIX___REDIS_HOST
    - secretKey: __APP_ENV_PREFIX___REDIS_PASS
      remoteRef:
        key: {{ .Values.externalSecrets.key }}
        property: __APP_ENV_PREFIX___REDIS_PASS
{{- end }}
{{- end }}
{{- if and .Values.externalSecrets.enabled .Values.migrate.enabled .Values.runtime.databaseEnabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "nk-backend.fullname" . }}-migration
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.store }}
    kind: ClusterSecretStore
  target:
    name: {{ include "nk-backend.fullname" . }}-migration
  data:
    - secretKey: __APP_ENV_PREFIX___DB_HOST
      remoteRef:
        key: {{ .Values.externalSecrets.key }}
        property: __APP_ENV_PREFIX___DB_HOST
    - secretKey: __APP_ENV_PREFIX___DB_USER
      remoteRef:
        key: {{ .Values.externalSecrets.key }}
        property: __APP_ENV_PREFIX___DB_ADMIN_USER
    - secretKey: __APP_ENV_PREFIX___DB_PASS
      remoteRef:
        key: {{ .Values.externalSecrets.key }}
        property: __APP_ENV_PREFIX___DB_ADMIN_PASS
    - secretKey: __APP_ENV_PREFIX___DB_BASE
      remoteRef:
        key: {{ .Values.externalSecrets.key }}
        property: __APP_ENV_PREFIX___DB_BASE
{{- end }}
{{- end }}
