{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nk-backend.fullname" . }}-default-deny
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nk-backend.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.ingressNamespace | quote }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  egress:
    - ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 3306
        - protocol: TCP
          port: 27017
        - protocol: TCP
          port: 4222
        - protocol: TCP
          port: 5672
        - protocol: TCP
          port: 9092
        - protocol: TCP
          port: 4317
        - protocol: TCP
          port: 8889
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}
